apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-sa
  namespace: jhub-dev
  labels:
    app: jupyterhub
    component: singleuser-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-sa-edit
  namespace: jhub-dev
subjects:
  - kind: ServiceAccount
    name: spark-sa
    namespace: jhub-dev
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
