apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-sa-cross-ns-edit
  namespace: default
subjects:
  - kind: ServiceAccount
    name: spark-sa
    namespace: jhub-dev
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
